import { FaSmile } from "react-icons/fa";
import { IoMdPeople } from "react-icons/io";
import { GiCycling } from "react-icons/gi";
import { MdFamilyRestroom } from "react-icons/md";
import { SiAnimalplanet } from "react-icons/si";
import { GiFruitBowl } from "react-icons/gi";
import { FaHeart } from "react-icons/fa";
import { FaTree } from "react-icons/fa";
import { GiWorld } from "react-icons/gi";
import { MdEmojiObjects } from "react-icons/md";
import { IoFlagSharp } from "react-icons/io5";
import { IoLogoUsd } from "react-icons/io";

export const emojis = [
  {
    groupName: "smileys",
    groupLogo: <FaSmile />,
    emojis: [
      { emoji: "😀", name: "Grinning Face" },
      { emoji: "😁", name: "Beaming Face With Smiling Eyes" },
      { emoji: "😂", name: "Face With Tears Of Joy" },
      { emoji: "🤣", name: "Rolling On The Floor Laughing" },
      { emoji: "😃", name: "Grinning Face With Big Eyes" },
      { emoji: "😄", name: "Grinning Face With Smiling Eyes" },
      { emoji: "😅", name: "Grinning Face With Sweat" },
      { emoji: "😆", name: "Grinning Squinting Face" },
      { emoji: "😉", name: "Winking Face" },
      { emoji: "😊", name: "Smiling Face With Smiling Eyes" },
      { emoji: "🥰", name: "Smiling Face with Hearts" },
      { emoji: "😋", name: "Face Savoring Food" },
      { emoji: "😎", name: "Smiling Face With Sunglasses" },
      { emoji: "😍", name: "Smiling Face With Heart-Eyes" },
      { emoji: "😘", name: "Face Blowing A Kiss" },
      { emoji: "😗", name: "Kissing Face" },
      { emoji: "😙", name: "Kissing Face With Smiling Eyes" },
      { emoji: "😚", name: "Kissing Face With Closed Eyes" },
      { emoji: "🙂", name: "Slightly Smiling Face" },
      { emoji: "🤗", name: "Hugging Face" },
      { emoji: "🤩", name: "Star-Struck" },
      { emoji: "🤔", name: "Thinking Face" },
      { emoji: "🤨", name: "Face With Raised Eyebrow" },
      { emoji: "😐", name: "Neutral Face" },
      { emoji: "😑", name: "Expressionless Face" },
      { emoji: "😶", name: "Face Without Mouth" },
      { emoji: "🙄", name: "Face With Rolling Eyes" },
      { emoji: "😏", name: "Smirking Face" },
      { emoji: "😣", name: "Persevering Face" },
      { emoji: "😥", name: "Sad But Relieved Face" },
      { emoji: "😮", name: "Face With Open Mouth" },
      { emoji: "🤐", name: "Zipper-Mouth Face" },
      { emoji: "😯", name: "Hushed Face" },
      { emoji: "😪", name: "Sleepy Face" },
      { emoji: "😫", name: "Tired Face" },
      { emoji: "🥱", name: "Yawning Face" },
      { emoji: "😴", name: "Sleeping Face" },
      { emoji: "😌", name: "Relieved Face" },
      { emoji: "😛", name: "Face With Tongue" },
      { emoji: "😜", name: "Winking Face With Tongue" },
      { emoji: "😝", name: "Squinting Face With Tongue" },
      { emoji: "🤤", name: "Drooling Face" },
      { emoji: "😒", name: "Unamused Face" },
      { emoji: "😓", name: "Downcast Face With Sweat" },
      { emoji: "😔", name: "Pensive Face" },
      { emoji: "😕", name: "Confused Face" },
      { emoji: "🙃", name: "Upside-Down Face" },
      { emoji: "🤑", name: "Money-Mouth Face" },
      { emoji: "😲", name: "Astonished Face" },
      { emoji: "☹️", name: "Frowning Face" },
      { emoji: "🙁", name: "Slightly Frowning Face" },
      { emoji: "😖", name: "Confounded Face" },
      { emoji: "😞", name: "Disappointed Face" },
      { emoji: "😟", name: "Worried Face" },
      { emoji: "😤", name: "Face With Steam From Nose" },
      { emoji: "😢", name: "Crying Face" },
      { emoji: "😭", name: "Loudly Crying Face" },
      { emoji: "😦", name: "Frowning Face With Open Mouth" },
      { emoji: "😧", name: "Anguished Face" },
      { emoji: "😨", name: "Fearful Face" },
      { emoji: "😩", name: "Weary Face" },
      { emoji: "🤯", name: "Exploding Head" },
      { emoji: "😬", name: "Grimacing Face" },
      { emoji: "😰", name: "Anxious Face With Sweat" },
      { emoji: "😱", name: "Face Screaming In Fear" },
      { emoji: "😳", name: "Flushed Face" },
      { emoji: "🤪", name: "Zany Face" },
      { emoji: "😵", name: "Dizzy Face" },
      { emoji: "😡", name: "Pouting Face" },
      { emoji: "😠", name: "Angry Face" },
      { emoji: "🤬", name: "Face With emojis On Mouth" },
      { emoji: "😷", name: "Face With Medical Mask" },
      { emoji: "🤒", name: "Face With Thermometer" },
      { emoji: "🤕", name: "Face With Head-Bandage" },
      { emoji: "🤢", name: "Nauseated Face" },
      { emoji: "🤮", name: "Face Vomiting" },
      { emoji: "🤧", name: "Sneezing Face" },
      { emoji: "😇", name: "Smiling Face With Halo" },
      { emoji: "🤠", name: "Cowboy Hat Face" },
      { emoji: "🤥", name: "Lying Face" },
      { emoji: "🤫", name: "Shushing Face" },
      { emoji: "🤭", name: "Face With Hand Over Mouth" },
      { emoji: "🧐", name: "Face With Monocle" },
      { emoji: "🤓", name: "Nerd Face" },
      { emoji: "😈", name: "Smiling Face With Horns" },
      { emoji: "👿", name: "Angry Face With Horns" },
      { emoji: "🤡", name: "Clown Face" },
      { emoji: "👹", name: "Ogre" },
      { emoji: "👺", name: "Goblin" },
      { emoji: "💀", name: "Skull" },
      { emoji: "☠️", name: "Skull And Crossbones" },
      { emoji: "👻", name: "Ghost" },
      { emoji: "👽", name: "Alien" },
      { emoji: "👾", name: "Alien Monster" },
      { emoji: "🤖", name: "Robot Face" },
      { emoji: "💩", name: "Pile Of Poo" },
      { emoji: "😺", name: "Grinning Cat Face" },
      { emoji: "😸", name: "Grinning Cat Face With Smiling Eyes" },
      { emoji: "😹", name: "Cat Face With Tears Of Joy" },
      { emoji: "😻", name: "Smiling Cat Face With Heart-Eyes" },
      { emoji: "😼", name: "Cat Face With Wry Smile" },
      { emoji: "😽", name: "Kissing Cat Face" },
      { emoji: "🙀", name: "Weary Cat Face" },
      { emoji: "😿", name: "Crying Cat Face" },
      { emoji: "😾", name: "Pouting Cat Face" },
      { emoji: "🙈", name: "See-No-Evil Monkey" },
      { emoji: "🙉", name: "Hear-No-Evil Monkey" },
      { emoji: "🙊", name: "Speak-No-Evil Monkey" },
      { emoji: "🗣️", name: "Speaking Head" },
      { emoji: "👤", name: "Bust in Silhouette" },
      { emoji: "👥", name: "Busts in Silhouette" },
      { emoji: "🫂", name: "People Hugging" },
      { emoji: "👣", name: "Footprints" },
      { emoji: "🦰", name: "Red Hair" },
      { emoji: "🦱", name: "Curly Hair" },
      { emoji: "🦳", name: "White Hair" },
      { emoji: "🦲", name: "Bald" },
    ],
  },

  {
    groupName: "people",
    groupLogo: <IoMdPeople />,
    emojis: [
      { emoji: "👨‍🦳", name: "Man: White Hair" },
      { emoji: "👨‍🦲", name: "Man: Bald" },
      { emoji: "👩", name: "Woman" },
      { emoji: "👩‍🦰", name: "Woman: Red Hair" },
      { emoji: "🧑‍🦰", name: "Person: Red Hair" },
      { emoji: "👩‍🦱", name: "Woman: Curly Hair" },
      { emoji: "🧑‍🦱", name: "Person: Curly Hair" },
      { emoji: "👩‍🦳", name: "Woman: White Hair" },
      { emoji: "🧑‍🦳", name: "Person: White Hair" },
      { emoji: "👩‍🦲", name: "Woman: Bald" },
      { emoji: "🧑‍🦲", name: "Person: Bald" },
      { emoji: "👱‍♀️", name: "Woman: Blond Hair" },
      { emoji: "👱‍♂️", name: "Man: Blond Hair" },
      { emoji: "🧓", name: "Older Person" },
      { emoji: "👴", name: "Old Man" },
      { emoji: "👵", name: "Old Woman" },
      { emoji: "🙍", name: "Person Frowning" },
      { emoji: "🙍‍♂️", name: "Man Frowning" },
      { emoji: "🙍‍♀️", name: "Woman Frowning" },
      { emoji: "🙎", name: "Person Pouting" },
      { emoji: "🙎‍♂️", name: "Man Pouting" },
      { emoji: "🙎‍♀️", name: "Woman Pouting" },
      { emoji: "🙅", name: "Person Gesturing No" },
      { emoji: "🙅‍♂️", name: "Man Gesturing No" },
      { emoji: "🙅‍♀️", name: "Woman Gesturing No" },
      { emoji: "🙆", name: "Person Gesturing Ok" },
      { emoji: "🙆‍♂️", name: "Man Gesturing Ok" },
      { emoji: "🙆‍♀️", name: "Woman Gesturing Ok" },
      { emoji: "💁", name: "Person Tipping Hand" },
      { emoji: "💁‍♂️", name: "Man Tipping Hand" },
      { emoji: "💁‍♀️", name: "Woman Tipping Hand" },
      { emoji: "🙋", name: "Person Raising Hand" },
      { emoji: "🙋‍♂️", name: "Man Raising Hand" },
      { emoji: "🙋‍♀️", name: "Woman Raising Hand" },
      { emoji: "🧏", name: "Deaf Person" },
      { emoji: "🧏‍♂️", name: "Deaf Man" },
      { emoji: "🧏‍♀️", name: "Deaf Woman" },
      { emoji: "🙇", name: "Person Bowing" },
      { emoji: "🙇‍♂️", name: "Man Bowing" },
      { emoji: "🙇‍♀️", name: "Woman Bowing" },
      { emoji: "🤦", name: "Person Facepalming" },
      { emoji: "🤦‍♂️", name: "Man Facepalming" },
      { emoji: "🤦‍♀️", name: "Woman Facepalming" },
      { emoji: "🤷", name: "Person Shrugging" },
      { emoji: "🤷‍♂️", name: "Man Shrugging" },
      { emoji: "🤷‍♀️", name: "Woman Shrugging" },
      { emoji: "🧑‍⚕️", name: "Health Worker" },
      { emoji: "👨‍⚕️", name: "Man Health Worker" },
      { emoji: "👩‍⚕️", name: "Woman Health Worker" },
      { emoji: "💏", name: "Kiss" },
      { emoji: "👩‍❤️‍💋‍👨", name: "Kiss: Woman, Man" },
      { emoji: "👨‍❤️‍💋‍👨", name: "Kiss: Man, Man" },
      { emoji: "👩‍❤️‍💋‍👩", name: "Kiss: Woman, Woman" },
      { emoji: "💑", name: "Couple with Heart" },
      { emoji: "👩‍❤️‍👨", name: "Couple with Heart: Woman, Man" },
      { emoji: "👨‍❤️‍👨", name: "Couple with Heart: Man, Man" },
      { emoji: "👩‍❤️‍👩", name: "Couple with Heart: Woman, Woman" },
      { emoji: "👪", name: "Family" },
      { emoji: "👨‍👩‍👦", name: "Family: Man, Woman, Boy" },
      { emoji: "👨‍👩‍👧", name: "Family: Man, Woman, Girl" },
      { emoji: "👨‍👩‍👧‍👦", name: "Family: Man, Woman, Girl, Boy" },
      { emoji: "👨‍👩‍👦‍👦", name: "Family: Man, Woman, Boy, Boy" },
      { emoji: "👨‍👩‍👧‍👧", name: "Family: Man, Woman, Girl, Girl" },
      { emoji: "👨‍👨‍👦", name: "Family: Man, Man, Boy" },
      { emoji: "👨‍👨‍👧", name: "Family: Man, Man, Girl" },
      { emoji: "👨‍👨‍👧‍👦", name: "Family: Man, Man, Girl, Boy" },
      { emoji: "👨‍👨‍👦‍👦", name: "Family: Man, Man, Boy, Boy" },
      { emoji: "👨‍👨‍👧‍👧", name: "Family: Man, Man, Girl, Girl" },
      { emoji: "👩‍👩‍👦", name: "Family: Woman, Woman, Boy" },
      { emoji: "👩‍👩‍👧", name: "Family: Woman, Woman, Girl" },
      { emoji: "👩‍👩‍👧‍👦", name: "Family: Woman, Woman, Girl, Boy" },
      { emoji: "👩‍👩‍👦‍👦", name: "Family: Woman, Woman, Boy, Boy" },
      { emoji: "👩‍👩‍👧‍👧", name: "Family: Woman, Woman, Girl, Girl" },
      { emoji: "👨‍👦", name: "Family: Man, Boy" },
      { emoji: "👨‍👦‍👦", name: "Family: Man, Boy, Boy" },
      { emoji: "👨‍👧", name: "Family: Man, Girl" },
      { emoji: "👨‍👧‍👦", name: "Family: Man, Girl, Boy" },
      { emoji: "👨‍👧‍👧", name: "Family: Man, Girl, Girl" },
      { emoji: "👩‍👦", name: "Family: Woman, Boy" },
      { emoji: "👩‍👦‍👦", name: "Family: Woman, Boy, Boy" },
      { emoji: "👩‍👧", name: "Family: Woman, Girl" },
      { emoji: "👩‍👧‍👦", name: "Family: Woman, Girl, Boy" },
      { emoji: "👩‍👧‍👧", name: "Family: Woman, Girl, Girl" },
      { emoji: "🧑‍🎓", name: "Student" },
      { emoji: "👨‍🎓", name: "Man Student" },
      { emoji: "👩‍🎓", name: "Woman Student" },
      { emoji: "🧑‍🏫", name: "Teacher" },
      { emoji: "👨‍🏫", name: "Man Teacher" },
      { emoji: "👩‍🏫", name: "Woman Teacher" },
      { emoji: "🧑‍⚖️", name: "Judge" },
      { emoji: "👨‍⚖️", name: "Man Judge" },
      { emoji: "👩‍⚖️", name: "Woman Judge" },
      { emoji: "🧑‍🌾", name: "Farmer" },
      { emoji: "👨‍🌾", name: "Man Farmer" },
      { emoji: "👩‍🌾", name: "Woman Farmer" },
      { emoji: "🧑‍🍳", name: "Cook" },
      { emoji: "👨‍🍳", name: "Man Cook" },
      { emoji: "👩‍🍳", name: "Woman Cook" },
      { emoji: "🧑‍🔧", name: "Mechanic" },
      { emoji: "👨‍🔧", name: "Man Mechanic" },
      { emoji: "👩‍🔧", name: "Woman Mechanic" },
      { emoji: "🧑‍🏭", name: "Factory Worker" },
      { emoji: "👨‍🏭", name: "Man Factory Worker" },
      { emoji: "👩‍🏭", name: "Woman Factory Worker" },
      { emoji: "🧑‍💼", name: "Office Worker" },
      { emoji: "👨‍💼", name: "Man Office Worker" },
      { emoji: "👩‍💼", name: "Woman Office Worker" },
      { emoji: "🧑‍🔬", name: "Scientist" },
      { emoji: "👨‍🔬", name: "Man Scientist" },
      { emoji: "👩‍🔬", name: "Woman Scientist" },
      { emoji: "🧑‍💻", name: "Technologist" },
      { emoji: "👨‍💻", name: "Man Technologist" },
      { emoji: "👩‍💻", name: "Woman Technologist" },
      { emoji: "🧑‍🎤", name: "Singer" },
      { emoji: "👨‍🎤", name: "Man Singer" },
      { emoji: "👩‍🎤", name: "Woman Singer" },
      { emoji: "🧑‍🎨", name: "Artist" },
      { emoji: "👨‍🎨", name: "Man Artist" },
      { emoji: "👩‍🎨", name: "Woman Artist" },
      { emoji: "🧑‍✈️", name: "Pilot" },
      { emoji: "👨‍✈️", name: "Man Pilot" },
      { emoji: "👩‍✈️", name: "Woman Pilot" },
      { emoji: "🧑‍🚀", name: "Astronaut" },
      { emoji: "👨‍🚀", name: "Man Astronaut" },
      { emoji: "👩‍🚀", name: "Woman Astronaut" },
      { emoji: "🧑‍🚒", name: "Firefighter" },
      { emoji: "👨‍🚒", name: "Man Firefighter" },
      { emoji: "👩‍🚒", name: "Woman Firefighter" },
      { emoji: "👮", name: "Police Officer" },
      { emoji: "👮‍♂️", name: "Man Police Officer" },
      { emoji: "👮‍♀️", name: "Woman Police Officer" },
      { emoji: "🕵️", name: "Detective" },
      { emoji: "🕵️‍♂️", name: "Man Detective" },
      { emoji: "🕵️‍♀️", name: "Woman Detective" },
      { emoji: "💂", name: "Guard" },
      { emoji: "💂‍♂️", name: "Man Guard" },
      { emoji: "💂‍♀️", name: "Woman Guard" },
      { emoji: "👷", name: "Construction Worker" },
      { emoji: "👷‍♂️", name: "Man Construction Worker" },
      { emoji: "👷‍♀️", name: "Woman Construction Worker" },
      { emoji: "🤴", name: "Prince" },
      { emoji: "👸", name: "Princess" },
      { emoji: "👳", name: "Person Wearing Turban" },
      { emoji: "👳‍♂️", name: "Man Wearing Turban" },
      { emoji: "👳‍♀️", name: "Woman Wearing Turban" },
      { emoji: "👲", name: "Person with Skullcap" },
      { emoji: "🧕", name: "Woman with Headscarf" },
      { emoji: "🤵", name: "Person in Tuxedo" },
      { emoji: "🤵‍♂️", name: "Man in Tuxedo" },
      { emoji: "🤵‍♀️", name: "Woman in Tuxedo" },
      { emoji: "👰", name: "Person with Veil" },
      { emoji: "👰‍♂️", name: "Man with Veil" },
      { emoji: "👰‍♀️", name: "Woman with Veil" },
      { emoji: "🤰", name: "Pregnant Woman" },
      { emoji: "🤱", name: "Breast-Feeding" },
      { emoji: "👩‍🍼", name: "Woman Feeding Baby" },
      { emoji: "👨‍🍼", name: "Man Feeding Baby" },
      { emoji: "🧑‍🍼", name: "Person Feeding Baby" },
      { emoji: "👼", name: "Baby Angel" },
      { emoji: "🎅", name: "Santa Claus" },
      { emoji: "🤶", name: "Mrs. Claus" },
      { emoji: "🧑‍🎄", name: "Mx Claus" },
      { emoji: "🦸", name: "Superhero" },
      { emoji: "🦸‍♂️", name: "Man Superhero" },
      { emoji: "🦸‍♀️", name: "Woman Superhero" },
      { emoji: "🦹", name: "Supervillain" },
      { emoji: "🦹‍♂️", name: "Man Supervillain" },
      { emoji: "🦹‍♀️", name: "Woman Supervillain" },
      { emoji: "🧙", name: "Mage" },
      { emoji: "🧙‍♂️", name: "Man Mage" },
      { emoji: "🧙‍♀️", name: "Woman Mage" },
      { emoji: "🧚", name: "Fairy" },
      { emoji: "🧚‍♂️", name: "Man Fairy" },
      { emoji: "🧚‍♀️", name: "Woman Fairy" },
      { emoji: "🧛", name: "Vampire" },
      { emoji: "🧛‍♂️", name: "Man Vampire" },
      { emoji: "🧛‍♀️", name: "Woman Vampire" },
      { emoji: "🧜", name: "Merperson" },
      { emoji: "🧜‍♂️", name: "Merman" },
      { emoji: "🧜‍♀️", name: "Mermaid" },
      { emoji: "🧝", name: "Elf" },
      { emoji: "🧝‍♂️", name: "Man Elf" },
      { emoji: "🧝‍♀️", name: "Woman Elf" },
      { emoji: "🧞", name: "Genie" },
      { emoji: "🧞‍♂️", name: "Man Genie" },
      { emoji: "🧞‍♀️", name: "Woman Genie" },
      { emoji: "🧟", name: "Zombie" },
      { emoji: "🧟‍♂️", name: "Man Zombie" },
      { emoji: "🧟‍♀️", name: "Woman Zombie" },
      { emoji: "🧌", name: "Troll" },
      { emoji: "💆", name: "Person Getting Massage" },
      { emoji: "💆‍♂️", name: "Man Getting Massage" },
      { emoji: "💆‍♀️", name: "Woman Getting Massage" },
      { emoji: "💇", name: "Person Getting Haircut" },
      { emoji: "💇‍♂️", name: "Man Getting Haircut" },
      { emoji: "💇‍♀️", name: "Woman Getting Haircut" },
      { emoji: "👶", name: "Baby" },
      { emoji: "🧒", name: "Child" },
      { emoji: "👦", name: "Boy" },
      { emoji: "👧", name: "Girl" },
      { emoji: "🧑", name: "Person" },
      { emoji: "👱", name: "Person: Blond Hair" },
      { emoji: "👨", name: "Man" },
      { emoji: "🧔", name: "Person: Beard" },
      { emoji: "👨‍🦰", name: "Man: Red Hair" },
      { emoji: "👨‍🦱", name: "Man: Curly Hair" },
    ],
  },

  {
    groupName: "workout",
    groupLogo: <GiCycling />,
    emojis: [
      { emoji: "🚶", name: "Person Walking" },
      { emoji: "🚶‍♂️", name: "Man Walking" },
      { emoji: "🚶‍♀️", name: "Woman Walking" },
      { emoji: "🧍", name: "Person Standing" },
      { emoji: "🧍‍♂️", name: "Man Standing" },
      { emoji: "🧍‍♀️", name: "Woman Standing" },
      { emoji: "🧎", name: "Person Kneeling" },
      { emoji: "🧎‍♂️", name: "Man Kneeling" },
      { emoji: "🧎‍♀️", name: "Woman Kneeling" },
      { emoji: "🧑‍🦯", name: "Person with White Cane" },
      { emoji: "👨‍🦯", name: "Man with White Cane" },
      { emoji: "👩‍🦯", name: "Woman with White Cane" },
      { emoji: "🧑‍🦼", name: "Person in Motorized Wheelchair" },
      { emoji: "👨‍🦼", name: "Man in Motorized Wheelchair" },
      { emoji: "👩‍🦼", name: "Woman in Motorized Wheelchair" },
      { emoji: "🧑‍🦽", name: "Person in Manual Wheelchair" },
      { emoji: "👨‍🦽", name: "Man in Manual Wheelchair" },
      { emoji: "👩‍🦽", name: "Woman in Manual Wheelchair" },
      { emoji: "🏃", name: "Person Running" },
      { emoji: "🏃‍♂️", name: "Man Running" },
      { emoji: "🏃‍♀️", name: "Woman Running" },
      { emoji: "🕴️", name: "Person in Suit Levitating" },
      { emoji: "👯", name: "People with Bunny Ears" },
      { emoji: "👯‍♂️", name: "Men with Bunny Ears" },
      { emoji: "👯‍♀️", name: "Women with Bunny Ears" },
      { emoji: "🧖", name: "Person in Steamy Room" },
      { emoji: "🧖‍♂️", name: "Man in Steamy Room" },
      { emoji: "🧖‍♀️", name: "Woman in Steamy Room" },
      { emoji: "🧗", name: "Person Climbing" },
      { emoji: "🧗‍♂️", name: "Man Climbing" },
      { emoji: "🧗‍♀️", name: "Woman Climbing" },
      { emoji: "🤺", name: "Person Fencing" },
      { emoji: "🏇", name: "Horse Racing" },
      { emoji: "⛷️", name: "Skier" },
      { emoji: "🏂", name: "Snowboarder" },
      { emoji: "🏌️", name: "Person Golfing" },
      { emoji: "🏌️‍♂️", name: "Man Golfing" },
      { emoji: "🏌️‍♀️", name: "Woman Golfing" },
      { emoji: "🏄", name: "Person Surfing" },
      { emoji: "🏄‍♂️", name: "Man Surfing" },
      { emoji: "🏄‍♀️", name: "Woman Surfing" },
      { emoji: "🚣", name: "Person Rowing Boat" },
      { emoji: "🚣‍♂️", name: "Man Rowing Boat" },
      { emoji: "🚣‍♀️", name: "Woman Rowing Boat" },
      { emoji: "🏊", name: "Person Swimming" },
      { emoji: "🏊‍♂️", name: "Man Swimming" },
      { emoji: "🏊‍♀️", name: "Woman Swimming" },
      { emoji: "⛹️", name: "Person Bouncing Ball" },
      { emoji: "⛹️‍♂️", name: "Man Bouncing Ball" },
      { emoji: "⛹️‍♀️", name: "Woman Bouncing Ball" },
      { emoji: "🏋️", name: "Person Lifting Weights" },
      { emoji: "🏋️‍♂️", name: "Man Lifting Weights" },
      { emoji: "🏋️‍♀️", name: "Woman Lifting Weights" },
      { emoji: "🚴", name: "Person Biking" },
      { emoji: "🚴‍♂️", name: "Man Biking" },
      { emoji: "🚴‍♀️", name: "Woman Biking" },
      { emoji: "🚵", name: "Person Mountain Biking" },
      { emoji: "🚵‍♂️", name: "Man Mountain Biking" },
      { emoji: "🚵‍♀️", name: "Woman Mountain Biking" },
      { emoji: "🤸", name: "Person Cartwheeling" },
      { emoji: "🤸‍♂️", name: "Man Cartwheeling" },
      { emoji: "🤸‍♀️", name: "Woman Cartwheeling" },
      { emoji: "🤼", name: "People Wrestling" },
      { emoji: "🤼‍♂️", name: "Men Wrestling" },
      { emoji: "🤼‍♀️", name: "Women Wrestling" },
      { emoji: "🤽", name: "Person Playing Water Polo" },
      { emoji: "🤽‍♂️", name: "Man Playing Water Polo" },
      { emoji: "🤽‍♀️", name: "Woman Playing Water Polo" },
      { emoji: "🤾", name: "Person Playing Handball" },
      { emoji: "🤾‍♂️", name: "Man Playing Handball" },
      { emoji: "🤾‍♀️", name: "Woman Playing Handball" },
      { emoji: "🧘", name: "Person in Lotus Position" },
      { emoji: "🧘‍♂️", name: "Man in Lotus Position" },
      { emoji: "🧘‍♀️", name: "Woman in Lotus Position" },
      { emoji: "🛀", name: "Person Taking Bath" },
      { emoji: "🛌", name: "Person in Bed" },
      { emoji: "🧑‍🤝‍🧑", name: "People Holding Hands" },
      { emoji: "👭", name: "Women Holding Hands" },
      { emoji: "👫", name: "Woman and Man Holding Hands" },
      { emoji: "👬", name: "Men Holding Hands" },
    ],
  },

  {
    groupName: "animal",
    groupLogo: <SiAnimalplanet />,

    emojis: [
      { emoji: "🐶", name: "Dog Face" },
      { emoji: "🐕", name: "Dog" },
      { emoji: "🦮", name: "Guide Dog" },
      { emoji: "🐕‍🦺", name: "Service Dog" },
      { emoji: "🐩", name: "Poodle" },
      { emoji: "🐺", name: "Wolf" },
      { emoji: "🦊", name: "Fox" },
      { emoji: "🦝", name: "Raccoon" },
      { emoji: "🐱", name: "Cat Face" },
      { emoji: "🐈", name: "Cat" },
      { emoji: "🐈‍⬛", name: "Black Cat" },
      { emoji: "🦁", name: "Lion" },
      { emoji: "🐯", name: "Tiger Face" },
      { emoji: "🐅", name: "Tiger" },
      { emoji: "🐆", name: "Leopard" },
      { emoji: "🐴", name: "Horse Face" },
      { emoji: "🐎", name: "Horse" },
      { emoji: "🦄", name: "Unicorn" },
      { emoji: "🦓", name: "Zebra" },
      { emoji: "🫏", name: "Donkey" },
      { emoji: "🦌", name: "Deer" },
      { emoji: "🫎", name: "Moose" },
      { emoji: "🫍", name: "Bison" },
      { emoji: "🐮", name: "Cow Face" },
      { emoji: "🐂", name: "Ox" },
      { emoji: "🐃", name: "Water Buffalo" },
      { emoji: "🐄", name: "Cow" },
      { emoji: "🐷", name: "Pig Face" },
      { emoji: "🐖", name: "Pig" },
      { emoji: "🐗", name: "Boar" },
      { emoji: "🐽", name: "Pig Nose" },
      { emoji: "🐏", name: "Ram" },
      { emoji: "🐑", name: "Ewe" },
      { emoji: "🐐", name: "Goat" },
      { emoji: "🐪", name: "Camel" },
      { emoji: "🐫", name: "Two-Hump Camel" },
      { emoji: "🦙", name: "Llama" },
      { emoji: "🦒", name: "Giraffe" },
      { emoji: "🫃", name: "Pregnant Man" },
      { emoji: "🫄", name: "Pregnant Person" },
      { emoji: "🐘", name: "Elephant" },
      { emoji: "🦣", name: "Mammoth" },
      { emoji: "🦏", name: "Rhinoceros" },
      { emoji: "🦛", name: "Hippopotamus" },
      { emoji: "🐭", name: "Mouse Face" },
      { emoji: "🐁", name: "Mouse" },
      { emoji: "🐀", name: "Rat" },
      { emoji: "🐹", name: "Hamster" },
      { emoji: "🐰", name: "Rabbit Face" },
      { emoji: "🐇", name: "Rabbit" },
      { emoji: "🐿️", name: "Chipmunk" },
      { emoji: "🦫", name: "Beaver" },
      { emoji: "🦔", name: "Hedgehog" },
      { emoji: "🦇", name: "Bat" },
      { emoji: "🐻", name: "Bear" },
      { emoji: "🐻‍❄️", name: "Polar Bear" },
      { emoji: "🐨", name: "Koala" },
      { emoji: "🐼", name: "Panda" },
      { emoji: "🦥", name: "Sloth" },
      { emoji: "🦦", name: "Otter" },
      { emoji: "🦨", name: "Skunk" },
      { emoji: "🦘", name: "Kangaroo" },
      { emoji: "🦬", name: "Bison" },
      { emoji: "🦬", name: "Bison" },
      { emoji: "🦡", name: "Badger" },
      { emoji: "🐾", name: "Paw Prints" },
      { emoji: "🦃", name: "Turkey" },
      { emoji: "🐔", name: "Chicken" },
      { emoji: "🐓", name: "Rooster" },
      { emoji: "🐣", name: "Hatching Chick" },
      { emoji: "🐤", name: "Baby Chick" },
      { emoji: "🐥", name: "Front-Facing Baby Chick" },
      { emoji: "🐦", name: "Bird" },
      { emoji: "🐧", name: "Penguin" },
      { emoji: "🕊️", name: "Dove" },
      { emoji: "🦅", name: "Eagle" },
      { emoji: "🦆", name: "Duck" },
      { emoji: "🦢", name: "Swan" },
      { emoji: "🦉", name: "Owl" },
      { emoji: "🦤", name: "Dodo" },
      { emoji: "🪶", name: "Feather" },
      { emoji: "🦩", name: "Flamingo" },
      { emoji: "🦚", name: "Peacock" },
      { emoji: "🦜", name: "Parrot" },
      { emoji: "🐸", name: "Frog" },
      { emoji: "🐊", name: "Crocodile" },
      { emoji: "🐢", name: "Turtle" },
      { emoji: "🦎", name: "Lizard" },
      { emoji: "🐍", name: "Snake" },
      { emoji: "🐲", name: "Dragon Face" },
      { emoji: "🐉", name: "Dragon" },
      { emoji: "🦕", name: "Sauropod" },
      { emoji: "🦖", name: "T-Rex" },
      { emoji: "🐳", name: "Spouting Whale" },
      { emoji: "🐋", name: "Whale" },
      { emoji: "🐬", name: "Dolphin" },
      { emoji: "🐟", name: "Fish" },
      { emoji: "🐠", name: "Tropical Fish" },
      { emoji: "🐡", name: "Blowfish" },
      { emoji: "🦈", name: "Shark" },
      { emoji: "🐙", name: "Octopus" },
      { emoji: "🐚", name: "Spiral Shell" },
      { emoji: "🪸", name: "Coral" },
      { emoji: "🦋", name: "Butterfly" },
      { emoji: "🐛", name: "Bug" },
      { emoji: "🐜", name: "Ant" },
      { emoji: "🐝", name: "Honeybee" },
      { emoji: "🪲", name: "Beetle" },
      { emoji: "🐞", name: "Lady Beetle" },
      { emoji: "🦗", name: "Cricket" },
      { emoji: "🪳", name: "Cockroach" },
      { emoji: "🕷️", name: "Spider" },
      { emoji: "🕸️", name: "Spider Web" },
      { emoji: "🦂", name: "Scorpion" },
      { emoji: "🦟", name: "Mosquito" },
      { emoji: "🪰", name: "Fly" },
      { emoji: "🪱", name: "Worm" },
      { emoji: "🦠", name: "Microbe" },
      { emoji: "🐌", name: "Snail" },
    ],
  },

  {
    groupName: "fruits",
    groupLogo: <GiFruitBowl />,

    emojis: [
      { emoji: "🍏", name: "Green Apple" },
      { emoji: "🍎", name: "Red Apple" },
      { emoji: "🍐", name: "Pear" },
      { emoji: "🍊", name: "Tangerine" },
      { emoji: "🍋", name: "Lemon" },
      { emoji: "🍌", name: "Banana" },
      { emoji: "🍉", name: "Watermelon" },
      { emoji: "🍇", name: "Grapes" },
      { emoji: "🍓", name: "Strawberry" },
      { emoji: "🫐", name: "Blueberries" },
      { emoji: "🍈", name: "Melon" },
      { emoji: "🍒", name: "Cherries" },
      { emoji: "🍑", name: "Peach" },
      { emoji: "🍍", name: "Pineapple" },
      { emoji: "🥭", name: "Mango" },
      { emoji: "🍅", name: "Tomato" },
      { emoji: "🍆", name: "Eggplant" },
      { emoji: "🥑", name: "Avocado" },
      { emoji: "🥥", name: "Coconut" },
      { emoji: "🍈", name: "Melon" },
      { emoji: "🍋", name: "Lemon" },
      { emoji: "🍊", name: "Orange" },
      { emoji: "🍌", name: "Banana" },
      { emoji: "🍉", name: "Watermelon" },
      { emoji: "🍇", name: "Grapes" },
      { emoji: "🍓", name: "Strawberry" },
      { emoji: "🫐", name: "Blueberries" },
      { emoji: "🍈", name: "Melon" },
      { emoji: "🍒", name: "Cherries" },
      { emoji: "🍑", name: "Peach" },
      { emoji: "🍍", name: "Pineapple" },
      { emoji: "🥭", name: "Mango" },
      { emoji: "🍅", name: "Tomato" },
      { emoji: "🍆", name: "Eggplant" },
      { emoji: "🥑", name: "Avocado" },
      { emoji: "🥥", name: "Coconut" },
      { emoji: "🥑", name: "Avocado" },
      { emoji: "🥦", name: "Broccoli" },
      { emoji: "🥕", name: "Carrot" },
      { emoji: "🌽", name: "Ear Of Corn" },
      { emoji: "🍆", name: "Eggplant" },
      { emoji: "🥒", name: "Cucumber" },
      { emoji: "🥬", name: "Leafy Green" },
      { emoji: "🥔", name: "Potato" },
      { emoji: "🍠", name: "Roasted Sweet Potato" },
      { emoji: "🍅", name: "Tomato" },
      { emoji: "🫑", name: "Bell Pepper" },
      { emoji: "🌶️", name: "Hot Pepper" },
      { emoji: "🧄", name: "Garlic" },
      { emoji: "🧅", name: "Onion" },
      { emoji: "🍄", name: "Mushroom" },
      { emoji: "🥜", name: "Peanuts" },
      { emoji: "🌰", name: "Chestnut" },
      { emoji: "🫘", name: "Beans" },
    ],
  },

  {
    groupName: "love",
    groupLogo: <FaHeart />,

    emojis: [
      { name: "Red Heart", emoji: "❤️" },
      { name: "Heart with Arrow", emoji: "💘" },
      { name: "Heart with Ribbon", emoji: "💝" },
      { name: "Sparkling Heart", emoji: "💖" },
      { name: "Growing Heart", emoji: "💗" },
      { name: "Beating Heart", emoji: "💓" },
      { name: "Revolving Hearts", emoji: "💞" },
      { name: "Two Hearts", emoji: "💕" },
      { name: "Heart Decoration", emoji: "💟" },
      { name: "Heart Exclamation", emoji: "❣️" },
      { name: "Broken Heart", emoji: "💔" },
      { name: "Heart on Fire", emoji: "❤️‍🔥" },
      { name: "Mending Heart", emoji: "❤️‍🩹" },
      { name: "Kiss Mark", emoji: "💋" },
      { name: "Kissing Face", emoji: "😗" },
      { name: "Kissing Face with Smiling Eyes", emoji: "😙" },
      { name: "Kissing Face with Closed Eyes", emoji: "😚" },
      { name: "Face Blowing a Kiss", emoji: "😘" },
      { name: "Couple with Heart: Man, Man", emoji: "👨‍❤️‍👨" },
      { name: "Couple with Heart: Woman, Woman", emoji: "👩‍❤️‍👩" },
      { name: "Couple with Heart: Man, Woman", emoji: "👩‍❤️‍👨" },
      { name: "Heart Hands", emoji: "🫶" },
      { name: "Smiling Face with Heart-Eyes", emoji: "😍" },
      { name: "Hugging Face", emoji: "🤗" },
      { name: "Heart with Stars", emoji: "💫❤️" },
      { name: "Love Letter", emoji: "💌" },
      { name: "Cupid", emoji: "🧚‍♂️" },
      { name: "Rose", emoji: "🌹" },
      { name: "Bouquet", emoji: "💐" },
      { name: "Wedding", emoji: "💒" },
      { name: "Ring", emoji: "💍" },
      { name: "Gem Stone", emoji: "💎" },
      { name: "Love Hotel", emoji: "🏩" },
      { name: "Chocolate", emoji: "🍫" },
      { name: "Strawberry", emoji: "🍓" },
      { name: "Cherry Blossom", emoji: "🌸" },
      { name: "Teddy Bear", emoji: "🧸" },
      { name: "Balloon", emoji: "🎈" },
      { name: "Ribbon", emoji: "🎀" },
      { name: "Gift", emoji: "🎁" },
      { name: "Wine Glass", emoji: "🍷" },
      { name: "Champagne", emoji: "🍾" },
      { name: "Two Hearts with Arrow", emoji: "💘💕" },
      { name: "Face with Hand over Mouth", emoji: "🤭" },
      { name: "Face with Hearts", emoji: "🥰" },
      { name: "Hand with Heart", emoji: "🤲❤️" },
      { name: "Heart with Flames", emoji: "🔥❤️" },
      { name: "Sparkle Heart", emoji: "✨❤️" },
      { name: "Pink Heart", emoji: "💗" },
      { name: "Lips", emoji: "👄" },
      { name: "Infinity Heart", emoji: "♾️❤️" },
      { name: "Candle", emoji: "🕯️" },
      { name: "Dove", emoji: "🕊️" },
      { name: "Blossom", emoji: "🌼" },
      { name: "Balloons", emoji: "🎈" },
      { name: "Fireworks", emoji: "🎆" },
      { name: "Confetti Ball", emoji: "🎊" },
      { name: "Sparkles", emoji: "✨" },
      { name: "Fire", emoji: "🔥" },
      { name: "Kiss", emoji: "💏" },
      { name: "Couple Kiss: Man, Woman", emoji: "👩‍❤️‍💋‍👨" },
      { name: "Couple Kiss: Man, Man", emoji: "👨‍❤️‍💋‍👨" },
      { name: "Couple Kiss: Woman, Woman", emoji: "👩‍❤️‍💋‍👩" },
      { name: "Couple with Heart", emoji: "💑" },
      { name: "Bouquet of Flowers", emoji: "💐" },
      { name: "Heart Balloon", emoji: "🎈❤️" },
      { name: "Sunflower", emoji: "🌻" },
      { name: "Hibiscus", emoji: "🌺" },
      { name: "Cherry", emoji: "🍒" },
      { name: "Smiling Face with 3 Hearts", emoji: "🥰" },
      { name: "Family", emoji: "👨‍👩‍👧‍👦" },
      { name: "Woman and Man Holding Hands", emoji: "👫" },
      { name: "Two Women Holding Hands", emoji: "👭" },
      { name: "Two Men Holding Hands", emoji: "👬" },
      { name: "Person with Heart", emoji: "🧑‍❤️" },
      { name: "Love You Gesture", emoji: "🤟" },
      { name: "Heart with Bow", emoji: "🎀❤️" },
      { name: "Bear Face", emoji: "🐻" },
      { name: "Dog Face", emoji: "🐶" },
      { name: "Cat Face", emoji: "🐱" },
      { name: "Rabbit Face", emoji: "🐰" },
      { name: "Monkey Face", emoji: "🐵" },
      { name: "Fox Face", emoji: "🦊" },
      { name: "Tiger Face", emoji: "🐯" },
      { name: "Panda Face", emoji: "🐼" },
      { name: "Heart Eyes", emoji: "😍" },
      { name: "Blowing a Kiss", emoji: "😘" },
      { name: "Purple Heart", emoji: "💜" },
      { name: "Blue Heart", emoji: "💙" },
      { name: "Green Heart", emoji: "💚" },
      { name: "Yellow Heart", emoji: "💛" },
      { name: "Orange Heart", emoji: "🧡" },
      { name: "Black Heart", emoji: "🖤" },
      { name: "White Heart", emoji: "🤍" },
      { name: "Brown Heart", emoji: "🤎" },
      { name: "Heart with Dots", emoji: "❤️‍🩹" },
      { name: "Heart with Bandage", emoji: "❤️‍🩹" },
      { name: "Heart with Ribbon Bow", emoji: "💝" },
      { name: "Cupid Arrow", emoji: "💘" },
      { name: "Love Hotel Icon", emoji: "🏩" },
      { name: "Love Note", emoji: "💌" },
      { name: "Embracing Heart", emoji: "❤️‍🤗" },
      { name: "Heart and Arrow", emoji: "❤️➸" },
      { name: "Kiss and Heart", emoji: "💋❤️" },
      { name: "Heart and Kisses", emoji: "❤️😘" },
    ],
  },

  {
    groupName: "tree",
    groupLogo: <FaTree />,

    emojis: [
      { emoji: "🌱", name: "Seedling" },
      { emoji: "🪴", name: "Potted Plant" },
      { emoji: "🌲", name: "Evergreen Tree" },
      { emoji: "🌳", name: "Deciduous Tree" },
      { emoji: "🌴", name: "Palm Tree" },
      { emoji: "🌵", name: "Cactus" },
      { emoji: "🌾", name: "Sheaf of Rice" },
      { emoji: "🌿", name: "Herb" },
      { emoji: "☘️", name: "Shamrock" },
      { emoji: "🍀", name: "Four Leaf Clover" },
      { emoji: "🍁", name: "Maple Leaf" },
      { emoji: "🍂", name: "Fallen Leaf" },
      { emoji: "🍃", name: "Leaf Fluttering in Wind" },
      { name: "Cherry Blossom", emoji: "🌸" },
      { name: "White Flower", emoji: "💮" },
      { name: "Rosette", emoji: "🏵️" },
      { name: "Rose", emoji: "🌹" },
      { name: "Hibiscus", emoji: "🌺" },
      { name: "Sunflower", emoji: "🌻" },
      { name: "Blossom", emoji: "🌼" },
      { name: "Tulip", emoji: "🌷" },
      { name: "Bouquet", emoji: "💐" },
      { name: "Wilted Flower", emoji: "🥀" },
      { name: "Lotus", emoji: "🪷" },
      { name: "Lavender", emoji: "🪻" },
      { name: "Daffodil", emoji: "🌼" },
      { name: "Cherry Blossom Branch", emoji: "🌸" },
      { name: "Potted Flower", emoji: "🪴" },
    ],
  },
  {
    groupName: "travel",
    groupLogo: <GiWorld />,

    emojis: [
      {
        emoji: "🌍",
        name: "Earth Globe Europe-Africa",
      },
      {
        emoji: "🌎",
        name: "Earth Globe Americas",
      },
      {
        emoji: "🌏",
        name: "Earth Globe Asia-Australia",
      },
      {
        emoji: "🌐",
        name: "Globe with Meridians",
      },
      {
        emoji: "🗺️",
        name: "World Map",
      },
      {
        emoji: "🏔️",
        name: "Snow-Capped Mountain",
      },
      {
        emoji: "🏕️",
        name: "Camping",
      },
      {
        emoji: "🏖️",
        name: "Beach with Umbrella",
      },
      {
        emoji: "🏜️",
        name: "Desert",
      },
      {
        emoji: "🏝️",
        name: "Desert Island",
      },
      {
        emoji: "🏞️",
        name: "National Park",
      },
      {
        emoji: "🌋",
        name: "Volcano",
      },
      {
        emoji: "🏟️",
        name: "Stadium",
      },
      {
        emoji: "🏛️",
        name: "Classical Building",
      },
      {
        emoji: "🏗️",
        name: "Building Construction",
      },
      { emoji: "🚗", name: "Car" },
      { emoji: "🚕", name: "Taxi" },
      { emoji: "🚙", name: "Sport Utility Vehicle" },
      { emoji: "🚌", name: "Bus" },
      { emoji: "🚎", name: "Trolleybus" },
      { emoji: "🏎️", name: "Racing Car" },
      { emoji: "🚓", name: "Police Car" },
      { emoji: "🚑", name: "Ambulance" },
      { emoji: "🚒", name: "Fire Engine" },
      { emoji: "🚐", name: "Minibus" },
      { emoji: "🛻", name: "Pickup Truck" },
      { emoji: "🚚", name: "Delivery Truck" },
      { emoji: "🚛", name: "Articulated Lorry" },
      { emoji: "🚜", name: "Tractor" },
      { emoji: "🦯", name: "White Cane" },
      { emoji: "🦽", name: "Manual Wheelchair" },
      { emoji: "🦼", name: "Motorized Wheelchair" },
      { emoji: "🛴", name: "Kick Scooter" },
      { emoji: "🚲", name: "Bicycle" },
      { emoji: "🛵", name: "Motor Scooter" },
      { emoji: "🏍️", name: "Motorcycle" },
      { emoji: "🛺", name: "Auto Rickshaw" },
      { emoji: "🚨", name: "Police Car Light" },
      { emoji: "🚔", name: "Oncoming Police Car" },
      { emoji: "🚍", name: "Oncoming Bus" },
      { emoji: "🚘", name: "Oncoming Car" },
      { emoji: "🚖", name: "Oncoming Taxi" },
      { emoji: "🛞", name: "Mountain Cableway" },
      { emoji: "🚡", name: "Aerial Tramway" },
      { emoji: "🚠", name: "Mountain Railway" },
      { emoji: "🚟", name: "Suspension Railway" },
      { emoji: "🚃", name: "Railway Car" },
      { emoji: "🚋", name: "Tram Car" },
      { emoji: "🚞", name: "Mountain Railway" },
      { emoji: "🚝", name: "Monorail" },
      { emoji: "🚄", name: "High-Speed Train" },
      { emoji: "🚅", name: "Bullet Train" },
      { emoji: "🚈", name: "Light Rail" },
      { emoji: "🚂", name: "Locomotive" },
      { emoji: "🚆", name: "Train" },
      { emoji: "🚇", name: "Metro" },
      { emoji: "🚊", name: "Tram" },
      { emoji: "🚉", name: "Station" },
      { emoji: "✈️", name: "Airplane" },
      { emoji: "🛫", name: "Airplane Departure" },
      { emoji: "🛬", name: "Airplane Arrival" },
      { emoji: "🛩️", name: "Small Airplane" },
      { emoji: "💺", name: "Seat" },
      { emoji: "🛰️", name: "Satellite" },
      { emoji: "🚀", name: "Rocket" },
      { emoji: "🛸", name: "Flying Saucer" },
      { emoji: "🚁", name: "Helicopter" },
      { emoji: "🛶", name: "Canoe" },
      { emoji: "⛵️", name: "Sailboat" },
      { emoji: "🚤", name: "Speedboat" },
      { emoji: "🛥️", name: "Motor Boat" },
      { emoji: "🛳️", name: "Passenger Ship" },
      { emoji: "⛴️", name: "Ferry" },
      { emoji: "🚢", name: "Ship" },
      { emoji: "⚓️", name: "Anchor" },
      { emoji: "🛟", name: "Luggage" },
      { emoji: "🪝", name: "Knot" },
      { emoji: "⛽️", name: "Fuel Pump" },
      { emoji: "🚧", name: "Construction" },
      { emoji: "🚦", name: "Traffic Light" },
      { emoji: "🚥", name: "Horizontal Traffic Light" },
      { emoji: "🚏", name: "Bus Stop" },
      { emoji: "🗺️", name: "World Map" },
      { emoji: "🗿", name: "Moyai" },
      { emoji: "🗽", name: "Statue of Liberty" },
      { emoji: "🗼", name: "Tokyo Tower" },
      { emoji: "🏰", name: "Castle" },
      { emoji: "🏯", name: "Japanese Castle" },
      { emoji: "🏟️", name: "Stadium" },
      { emoji: "🎡", name: "Ferris Wheel" },
      { emoji: "🎢", name: "Roller Coaster" },
      { emoji: "🛝", name: "Bellhop Bell" },
      { emoji: "🎠", name: "Carousel Horse" },
      { emoji: "⛲️", name: "Fountain" },
      { emoji: "⛱️", name: "Umbrella on Ground" },
      { emoji: "🏖️", name: "Beach with Umbrella" },
      { emoji: "🏝️", name: "Desert Island" },
      { emoji: "🏜️", name: "Desert" },
      { emoji: "🌋", name: "Volcano" },
      { emoji: "⛰️", name: "Mountain" },
      { emoji: "🏔️", name: "Snow-Capped Mountain" },
      { emoji: "🗻", name: "Mount Fuji" },
      { emoji: "🏕️", name: "Camping" },
      { emoji: "⛺️", name: "Tent" },
      { emoji: "🛖", name: "Hut" },
      { emoji: "🏠", name: "House" },
      { emoji: "🏡", name: "House with Garden" },
      { emoji: "🏘️", name: "Houses" },
      { emoji: "🏚️", name: "Derelict House" },
      { emoji: "🏗️", name: "Building Construction" },
      { emoji: "🏭", name: "Factory" },
      { emoji: "🏢", name: "Office Building" },
      { emoji: "🏬", name: "Department Store" },
      { emoji: "🏣", name: "Japanese Post Office" },
      { emoji: "🏤", name: "Post Office" },
      { emoji: "🏥", name: "Hospital" },
      { emoji: "🏦", name: "Bank" },
      { emoji: "🏨", name: "Hotel" },
      { emoji: "🏪", name: "Convenience Store" },
      { emoji: "🏫", name: "School" },
      { emoji: "🏩", name: "Love Hotel" },
      { emoji: "💒", name: "Wedding" },
      { emoji: "🏛️", name: "Classical Building" },
      { emoji: "⛪️", name: "Church" },
      { emoji: "🕌", name: "Mosque" },
      { emoji: "🕍", name: "Synagogue" },
      { emoji: "🛕", name: "Hindu Temple" },
      { emoji: "🕋", name: "Kaaba" },
      { emoji: "⛩️", name: "Shinto Shrine" },
      { emoji: "🛤️", name: "Railway Track" },
      { emoji: "🛣️", name: "Motorway" },
      { emoji: "🗾", name: "Map of Japan" },
      { emoji: "🎑", name: "Rice Scene" },
      { emoji: "🏞️", name: "National Park" },
      { emoji: "🌅", name: "Sunrise" },
      { emoji: "🌄", name: "Sunrise Over Mountains" },
      { emoji: "🌠", name: "Shooting Star" },
      { emoji: "🎇", name: "Fireworks" },
      { emoji: "🎆", name: "Fireworks" },
      { emoji: "🌇", name: "Sunset" },
      { emoji: "🌆", name: "Cityscape at Dusk" },
      { emoji: "🏙️", name: "Cityscape" },
      { emoji: "🌃", name: "Night with Stars" },
      { emoji: "🌌", name: "Milky Way" },
      { emoji: "🌉", name: "Bridge at Night" },
      { emoji: "🌁", name: "Foggy" },
    ],
  },
  {
    groupName: "objects",
    groupLogo: <MdEmojiObjects />,
    emojis: [
      {
        emoji: "💡",
        name: "Light Bulb",
      },
      {
        emoji: "🔦",
        name: "Flashlight",
      },
      {
        emoji: "🕯️",
        name: "Candle",
      },
      {
        emoji: "🪔",
        name: "Diya Lamp",
      },
      {
        emoji: "📷",
        name: "Camera",
      },
      {
        emoji: "🔍",
        name: "Magnifying Glass Tilted Left",
      },
      {
        emoji: "🔭",
        name: "Telescope",
      },
      {
        emoji: "🔬",
        name: "Microscope",
      },
      {
        emoji: "📡",
        name: "Satellite Antenna",
      },
      {
        emoji: "🎥",
        name: "Movie Camera",
      },
      {
        emoji: "📺",
        name: "Television",
      },
      {
        emoji: "📻",
        name: "Radio",
      },
      {
        emoji: "⏰",
        name: "Alarm Clock",
      },
      {
        emoji: "🕰️",
        name: "Mantelpiece Clock",
      },
      {
        emoji: "🌡️",
        name: "Thermometer",
      },
      { emoji: "⌚️", name: "Watch" },
      { emoji: "📱", name: "Mobile Phone" },
      { emoji: "📲", name: "Mobile Phone with Arrow" },
      { emoji: "💻", name: "Laptop" },
      { emoji: "⌨️", name: "Keyboard" },
      { emoji: "🖥️", name: "Desktop Computer" },
      { emoji: "🖨️", name: "Printer" },
      { emoji: "🖱️", name: "Computer Mouse" },
      { emoji: "🖲️", name: "Trackball" },
      { emoji: "🕹️", name: "Joystick" },
      { emoji: "🗜️", name: "Vice" },
      { emoji: "💽", name: "Computer Disk" },
      { emoji: "💾", name: "Floppy Disk" },
      { emoji: "💿", name: "Optical Disk" },
      { emoji: "📀", name: "DVD" },
      { emoji: "📼", name: "Videocassette" },
      { emoji: "📸", name: "Camera with Flash" },
      { emoji: "📹", name: "Video Camera" },
      { emoji: "🎥", name: "Movie Camera" },
      { emoji: "📽️", name: "Film Projector" },
      { emoji: "🎞️", name: "Film Frames" },
      { emoji: "📞", name: "Telephone Receiver" },
      { emoji: "☎️", name: "Telephone" },
      { emoji: "📟", name: "Pager" },
      { emoji: "📠", name: "Fax Machine" },
      { emoji: "📺", name: "Television" },
      { emoji: "📻", name: "Radio" },
      { emoji: "🎙️", name: "Studio Microphone" },
      { emoji: "🎚️", name: "Level Slider" },
      { emoji: "🎛️", name: "Control Knobs" },
      { emoji: "🧭", name: "Compass" },
      { emoji: "⏱️", name: "Stopwatch" },
      { emoji: "⏲️", name: "Timer Clock" },
      { emoji: "⏰", name: "Alarm Clock" },
      { emoji: "🕰️", name: "Mantelpiece Clock" },
      { emoji: "⌛️", name: "Hourglass Done" },
      { emoji: "⏳", name: "Hourglass Not Done" },
      { emoji: "📡", name: "Satellite Antenna" },
      { emoji: "🔋", name: "Battery" },
      { emoji: "🪫", name: "Toothbrush" },
      { emoji: "🔌", name: "Electric Plug" },
      { emoji: "💡", name: "Light Bulb" },
      { emoji: "🔦", name: "Flashlight" },
      { emoji: "🕯️", name: "Candle" },
      { emoji: "🪔", name: "Wastebasket" },
      { emoji: "🧯", name: "Fire Extinguisher" },
      { emoji: "🛢️", name: "Oil Drum" },
      { emoji: "🛍️", name: "Shopping Bags" },
      { emoji: "💸", name: "Money with Wings" },
      { emoji: "💵", name: "Dollar Banknote" },
      { emoji: "💴", name: "Yen Banknote" },
      { emoji: "💶", name: "Euro Banknote" },
      { emoji: "💷", name: "Pound Banknote" },
      { emoji: "🪙", name: "Coin" },
      { emoji: "💰", name: "Money Bag" },
      { emoji: "💳", name: "Credit Card" },
      { emoji: "💎", name: "Gem Stone" },
      { emoji: "⚖️", name: "Balance Scale" },
      { emoji: "🪮", name: "Plunger" },
      { emoji: "🪜", name: "Bucket" },
      { emoji: "🧰", name: "Toolkit" },
      { emoji: "🪛", name: "Screwdriver" },
      { emoji: "🔧", name: "Wrench" },
      { emoji: "🔨", name: "Hammer" },
      { emoji: "⚒️", name: "Hammer and Pick" },
      { emoji: "🛠️", name: "Hammer and Wrench" },
      { emoji: "⛏️", name: "Pick" },
      { emoji: "🪚", name: "Hatchet" },
      { emoji: "🔩", name: "Nut and Bolt" },
      { emoji: "⚙️", name: "Gear" },
      { emoji: "🪤", name: "Mouse Trap" },
      { emoji: "🧱", name: "Brick" },
      { emoji: "⛓️", name: "Chains" },
      { emoji: "⛓️‍💥", name: "Chains and Fire" },
      { emoji: "🧲", name: "Magnet" },
      { emoji: "🔫", name: "Pistol" },
      { emoji: "💣", name: "Bomb" },
      { emoji: "🧨", name: "Firecracker" },
      { emoji: "🪓", name: "Axe" },
      { emoji: "🔪", name: "Kitchen Knife" },
      { emoji: "🗡️", name: "Dagger" },
      { emoji: "⚔️", name: "Crossed Swords" },
      { emoji: "🛡️", name: "Shield" },
      { emoji: "🚬", name: "Cigarette" },
      { emoji: "⚰️", name: "Coffin" },
      { emoji: "🪦", name: "Headstone" },
      { emoji: "⚱️", name: "Funeral Urn" },
      { emoji: "🏺", name: "Amphora" },
      { emoji: "🔮", name: "Crystal Ball" },
      { emoji: "📿", name: "Prayer Beads" },
      { emoji: "🧿", name: "Nazar Amulet" },
      { emoji: "🪬", name: "DNA" },
      { emoji: "💈", name: "Barber Pole" },
      { emoji: "⚗️", name: "Alembic" },
      { emoji: "🔭", name: "Telescope" },
      { emoji: "🔬", name: "Microscope" },
      { emoji: "🕳️", name: "Hole" },
      { emoji: "🩹", name: "Adhesive Bandage" },
      { emoji: "🩺", name: "Stethoscope" },
      { emoji: "🩻", name: "Syringe" },
      { emoji: "🩼", name: "Petri Dish" },
      { emoji: "💊", name: "Pill" },
      { emoji: "💉", name: "Syringe" },
      { emoji: "🩸", name: "Drop of Blood" },
      { emoji: "🧬", name: "DNA Double Helix" },
      { emoji: "🦠", name: "Microbe" },
      { emoji: "🧫", name: "Petri Dish" },
      { emoji: "🧪", name: "Test Tube" },
      { emoji: "🌡️", name: "Thermometer" },
      { emoji: "🧹", name: "Broom" },
      { emoji: "🪠", name: "Plunger" },
      { emoji: "🧺", name: "Basket" },
      { emoji: "🧻", name: "Toilet Paper" },
      { emoji: "🚽", name: "Toilet" },
      { emoji: "🚰", name: "Potable Water" },
      { emoji: "🚿", name: "Shower" },
      { emoji: "🛁", name: "Bathtub" },
      { emoji: "🛀", name: "Person Taking Bath" },
      { emoji: "🧼", name: "Soap" },
      { emoji: "🪥", name: "Razor" },
      { emoji: "🪒", name: "Lotion Bottle" },
      { emoji: "🧽", name: "Sponge" },
      { emoji: "🪣", name: "Bucket" },
      { emoji: "🧴", name: "Lotion Bottle" },
      { emoji: "🛎️", name: "Bellhop Bell" },
      { emoji: "🔑", name: "Key" },
      { emoji: "🗝️", name: "Old Key" },
      { emoji: "🚪", name: "Door" },
      { emoji: "🪑", name: "Chair" },
      { emoji: "🛋️", name: "Couch and Lamp" },
      { emoji: "🛏️", name: "Bed" },
      { emoji: "🛌", name: "Person in Bed" },
      { emoji: "🧸", name: "Teddy Bear" },
      { emoji: "🪆", name: "Nesting Dolls" },
      { emoji: "🖼️", name: "Framed Picture" },
      { emoji: "🪞", name: "Elevator" },
      { emoji: "🪟", name: "Elevator" },
      { emoji: "🛍️", name: "Shopping Bags" },
      { emoji: "🛒", name: "Shopping Cart" },
      { emoji: "🎁", name: "Wrapped Gift" },
      { emoji: "🎈", name: "Balloon" },
      { emoji: "🎏", name: "Carp Streamer" },
      { emoji: "🎀", name: "Ribbon" },
      { emoji: "🪄", name: "Magic Wand" },
      { emoji: "🪅", name: "Pinata" },
      { emoji: "🎊", name: "Confetti Ball" },
      { emoji: "🎉", name: "Party Popper" },
      { emoji: "🪩", name: "Accordion" },
      { emoji: "🎎", name: "Japanese Dolls" },
      { emoji: "🏮", name: "Red Paper Lantern" },
      { emoji: "🎐", name: "Wind Chime" },
      { emoji: "🧧", name: "Red Envelope" },
      { emoji: "✉️", name: "Envelope" },
      { emoji: "📩", name: "Envelope with Arrow" },
      { emoji: "📨", name: "Incoming Envelope" },
      { emoji: "📧", name: "E-mail" },
      { emoji: "💌", name: "Love Letter" },
      { emoji: "📥", name: "Inbox Tray" },
      { emoji: "📤", name: "Outbox Tray" },
      { emoji: "📦", name: "Package" },
      { emoji: "🏷️", name: "Label" },
      { emoji: "🪧", name: "Bookmark" },
      { emoji: "📪", name: "Closed Mailbox with Lowered Flag" },
      { emoji: "📫", name: "Closed Mailbox with Raised Flag" },
      { emoji: "📬", name: "Open Mailbox with Raised Flag" },
      { emoji: "📭", name: "Open Mailbox with Lowered Flag" },
      { emoji: "📮", name: "Postbox" },
      { emoji: "📯", name: "Postal Horn" },
      { emoji: "📜", name: "Scroll" },
      { emoji: "📃", name: "Page with Curl" },
      { emoji: "📄", name: "Page Facing Up" },
      { emoji: "📑", name: "Bookmark Tabs" },
      { emoji: "🧾", name: "Receipt" },
      { emoji: "📊", name: "Bar Chart" },
      { emoji: "📈", name: "Chart Increasing" },
      { emoji: "📉", name: "Chart Decreasing" },
      { emoji: "🗒️", name: "Spiral Notepad" },
      { emoji: "🗓️", name: "Spiral Calendar" },
      { emoji: "📆", name: "Tear-Off Calendar" },
      { emoji: "📅", name: "Calendar" },
      { emoji: "🗑️", name: "Wastebasket" },
      { emoji: "🪪", name: "Metered Mail" },
      { emoji: "📇", name: "Card Index" },
      { emoji: "🗃️", name: "Card File Box" },
      { emoji: "🗳️", name: "Ballot Box with Ballot" },
      { emoji: "🗄️", name: "File Cabinet" },
      { emoji: "📋", name: "Clipboard" },
      { emoji: "📁", name: "File Folder" },
      { emoji: "📂", name: "Open File Folder" },
      { emoji: "🗂️", name: "Card Index Dividers" },
      { emoji: "🗞️", name: "Rolled-Up Newspaper" },
      { emoji: "📰", name: "Newspaper" },
      { emoji: "📓", name: "Notebook" },
      { emoji: "📔", name: "Notebook with Decorative Cover" },
      { emoji: "📒", name: "Ledger" },
      { emoji: "📕", name: "Closed Book" },
      { emoji: "📗", name: "Green Book" },
      { emoji: "📘", name: "Blue Book" },
      { emoji: "📙", name: "Orange Book" },
      { emoji: "📚", name: "Books" },
      { emoji: "📖", name: "Open Book" },
      { emoji: "🔖", name: "Bookmark" },
      { emoji: "🧷", name: "Safety Pin" },
      { emoji: "🔗", name: "Link" },
      { emoji: "📎", name: "Paperclip" },
      { emoji: "🖇️", name: "Linked Paperclips" },
      { emoji: "📐", name: "Triangular Ruler" },
      { emoji: "📏", name: "Straight Ruler" },
      { emoji: "🧮", name: "Abacus" },
      { emoji: "📌", name: "Pushpin" },
      { emoji: "📍", name: "Round Pushpin" },
      { emoji: "✂️", name: "Scissors" },
      { emoji: "🖊️", name: "Pen" },
      { emoji: "🖋️", name: "Fountain Pen" },
      { emoji: "✒️", name: "Black Nib" },
      { emoji: "🖌️", name: "Paintbrush" },
      { emoji: "🖍️", name: "Crayon" },
      { emoji: "📝", name: "Memo" },
      { emoji: "✏️", name: "Pencil" },
      { emoji: "🔍", name: "Magnifying Glass Tilted Left" },
      { emoji: "🔎", name: "Magnifying Glass Tilted Right" },
      { emoji: "🔏", name: "Locked with Pen" },
      { emoji: "🔐", name: "Locked with Key" },
      { emoji: "🔒", name: "Locked" },
      { emoji: "🔓", name: "Unlocked" },
    ],
  },
  {
    groupName: "symbols",
    groupLogo: <IoLogoUsd />,
    emojis: [
      { emoji: "❤️", name: "Red Heart" },
      { emoji: "🩷", name: "White Heart" },
      { emoji: "🧡", name: "Orange Heart" },
      { emoji: "💛", name: "Yellow Heart" },
      { emoji: "💚", name: "Green Heart" },
      { emoji: "💙", name: "Blue Heart" },
      { emoji: "🩵", name: "Purple Heart" },
      { emoji: "💜", name: "Purple Heart" },
      { emoji: "🖤", name: "Black Heart" },
      { emoji: "🩶", name: "Brown Heart" },
      { emoji: "🤍", name: "White Heart" },
      { emoji: "🤎", name: "Brown Heart" },
      { emoji: "❤️‍🔥", name: "Heart on Fire" },
      { emoji: "❤️‍🩹", name: "Mending Heart" },
      { emoji: "💔", name: "Broken Heart" },
      { emoji: "❣️", name: "Heart Exclamation" },
      { emoji: "💕", name: "Two Hearts" },
      { emoji: "💞", name: "Revolving Hearts" },
      { emoji: "💓", name: "Beating Heart" },
      { emoji: "💗", name: "Growing Heart" },
      { emoji: "💖", name: "Sparkling Heart" },
      { emoji: "💘", name: "Heart with Arrow" },
      { emoji: "💝", name: "Heart with Ribbon" },
      {
        emoji: "₹",
        name: "Indian Rupee Sign",
      },

      {
        emoji: "💱",
        name: "Currency Exchange",
      },
      {
        emoji: "🏦",
        name: "Bank",
      },
      {
        emoji: "🏧",
        name: "ATM Sign",
      },
      {
        emoji: "💸",
        name: "Money with Wings",
      },
      {
        emoji: "💳",
        name: "Credit Card",
      },
      {
        emoji: "💹",
        name: "Chart Increasing with Yen",
      },
      {
        emoji: "💲",
        name: "Heavy Dollar Sign",
      },
      {
        emoji: "✅",
        name: "White Heavy Check Mark",
      },
      {
        emoji: "🚫",
        name: "No Entry Sign",
      },
      {
        emoji: "💰",
        name: "Money Bag",
      },
      { emoji: "💟", name: "Heart Decoration" },
      { emoji: "☮️", name: "Peace emoji" },
      { emoji: "✝️", name: "Latin Cross" },
      { emoji: "☪️", name: "Star and Crescent" },
      { emoji: "🪯", name: "Incense" },
      { emoji: "🕉️", name: "Om" },
      { emoji: "☸️", name: "Wheel of Dharma" },
      { emoji: "✡️", name: "Star of David" },
      { emoji: "🔯", name: "Dotted Six-Pointed Star" },
      { emoji: "🕎", name: "Menorah" },
      { emoji: "☯️", name: "Yin Yang" },
      { emoji: "☦️", name: "Orthodox Cross" },
      { emoji: "🛐", name: "Place of Worship" },
      { emoji: "⛎", name: "Ophiuchus" },
      { emoji: "♈️", name: "Aries" },
      { emoji: "♉️", name: "Taurus" },
      { emoji: "♊️", name: "Gemini" },
      { emoji: "♋️", name: "Cancer" },
      { emoji: "♌️", name: "Leo" },
      { emoji: "♍️", name: "Virgo" },
      { emoji: "♎️", name: "Libra" },
      { emoji: "♏️", name: "Scorpio" },
      { emoji: "♐️", name: "Sagittarius" },
      { emoji: "♑️", name: "Capricorn" },
      { emoji: "♒️", name: "Aquarius" },
      { emoji: "♓️", name: "Pisces" },
      { emoji: "🆔", name: "ID Button" },
      { emoji: "⚛️", name: "Atom Symbol" },
      { emoji: "🉑", name: "Japanese Acceptable Button" },
      { emoji: "☢️", name: "Radioactive" },
      { emoji: "☣️", name: "Biohazard" },
      { emoji: "📴", name: "Mobile Phone Off" },
      { emoji: "📳", name: "Vibration Mode" },
      { emoji: "🈶", name: "Japanese “Not Free of Charge” Button" },
      { emoji: "🈚️", name: "Japanese “Free of Charge” Button" },
      { emoji: "🈸", name: "Japanese “Application” Button" },
      { emoji: "🈺", name: "Japanese “Open for Business” Button" },
      { emoji: "🈷️", name: "Japanese “Monthly Amount” Button" },
      { emoji: "✴️", name: "Eight-Pointed Star" },
      { emoji: "🆚", name: "VS Button" },
      { emoji: "💮", name: "White Flower" },
      { emoji: "🉐", name: "Japanese “Bargain” Button" },
      { emoji: "㊙️", name: "Japanese “Secret” Button" },
      { emoji: "㊗️", name: "Japanese “Congratulations” Button" },
      { emoji: "🈴", name: "Japanese “Passing Grade” Button" },
      { emoji: "🈵", name: "Japanese “No Vacancy” Button" },
      { emoji: "🈹", name: "Japanese “Discount” Button" },
      { emoji: "🈲", name: "Japanese “Prohibited” Button" },
      { emoji: "🅰️", name: "A Button (Blood Type)" },
      { emoji: "🅱️", name: "B Button (Blood Type)" },
      { emoji: "🆎", name: "AB Button (Blood Type)" },
      { emoji: "🆑", name: "CL Button" },
      { emoji: "🅾️", name: "O Button (Blood Type)" },
      { emoji: "🆘", name: "SOS Button" },
      { emoji: "❌", name: "Cross Mark" },
      { emoji: "⭕️", name: "Heavy Large Circle" },
      { emoji: "🛑", name: "Stop Sign" },
      { emoji: "⛔️", name: "No Entry" },
      { emoji: "📛", name: "Name Badge" },
      { emoji: "🚫", name: "No Entry Sign" },
      { emoji: "💯", name: "Hundred Points" },
      { emoji: "💢", name: "Anger Symbol" },
      { emoji: "♨️", name: "Hot Springs" },
      { emoji: "🚷", name: "No Pedestrians" },
      { emoji: "🚯", name: "No Littering" },
      { emoji: "🚳", name: "No Bicycles" },
      { emoji: "🚱", name: "Non-Potable Water" },
      { emoji: "🔞", name: "No One Under Eighteen" },
      { emoji: "📵", name: "No Mobile Phones" },
      { emoji: "🚭", name: "No Smoking" },
      { emoji: "❗️", name: "Exclamation Mark" },
      { emoji: "❕", name: "White Exclamation Mark" },
      { emoji: "❓", name: "Question Mark" },
      { emoji: "❔", name: "White Question Mark" },
      { emoji: "‼️", name: "Double Exclamation Mark" },
      { emoji: "⁉️", name: "Exclamation Question Mark" },
      { emoji: "🔅", name: "Dim Button" },
      { emoji: "🔆", name: "Bright Button" },
      { emoji: "〽️", name: "Part Alternation Mark" },
      { emoji: "⚠️", name: "Warning" },
      { emoji: "🚸", name: "Children Crossing" },
      { emoji: "🔱", name: "Trident Emblem" },
      { emoji: "⚜️", name: "Fleur-de-lis" },
      { emoji: "🔰", name: "Japanese Symbol for Beginner" },
      { emoji: "♻️", name: "Recycling Symbol" },
      { emoji: "✅", name: "Check Mark Button" },
      { emoji: "🈯️", name: "Japanese “Reserved” Button" },
      { emoji: "💹", name: "Chart Increasing with Yen" },
      { emoji: "❇️", name: "Sparkle" },
      { emoji: "✳️", name: "Eight-Spoked Asterisk" },
      { emoji: "❎", name: "Cross Mark Button" },
      { emoji: "🌐", name: "Globe with Meridians" },
      { emoji: "💠", name: "Diamond Shape with a Dot Inside" },
      { emoji: "Ⓜ️", name: "Circle with M" },
      { emoji: "🌀", name: "Cyclone" },
      { emoji: "💤", name: "Zzz" },
      { emoji: "🏧", name: "ATM Sign" },
      { emoji: "🚾", name: "Water Closet" },
      { emoji: "♿️", name: "Wheelchair Symbol" },
      { emoji: "🅿️", name: "P Button" },
      { emoji: "🛗", name: "Elevator" },
      { emoji: "🈳", name: "Japanese “Vacancy” Button" },
      { emoji: "🈂️", name: "Japanese “Service Charge” Button" },
      { emoji: "🛂", name: "Passport Control" },
      { emoji: "🛃", name: "Customs" },
      { emoji: "🛄", name: "Baggage Claim" },
      { emoji: "🛅", name: "Left Luggage" },
      { emoji: "🚹", name: "Men’s Room" },
      { emoji: "🚺", name: "Women’s Room" },
      { emoji: "🚼", name: "Baby Symbol" },
      { emoji: "⚧", name: "Transgender Symbol" },
      { emoji: "🚻", name: "Restroom" },
      { emoji: "🚮", name: "Litter in Bin Sign" },
      { emoji: "🎦", name: "Cinema" },
      { emoji: "🛜", name: "Left-Handed Interlaced Pentagram" },
      { emoji: "📶", name: "Antenna Bars" },
      { emoji: "🈁", name: "Japanese “Here” Button" },
      { emoji: "🔣", name: "Input Symbols" },
      { emoji: "ℹ️", name: "Information" },
      { emoji: "🔤", name: "Input Latin Letters" },
      { emoji: "🔡", name: "Input Latin Lowercase" },
      { emoji: "🔠", name: "Input Latin Uppercase" },
      { emoji: "🆖", name: "NG Button" },
      { emoji: "🆗", name: "OK Button" },
      { emoji: "🆙", name: "Up Button" },
      { emoji: "🆒", name: "Cool Button" },
      { emoji: "🆕", name: "New Button" },
      { emoji: "🆓", name: "Free Button" },
      { emoji: "0️⃣", name: "Keycap: 0" },
      { emoji: "1️⃣", name: "Keycap: 1" },
      { emoji: "2️⃣", name: "Keycap: 2" },
      { emoji: "3️⃣", name: "Keycap: 3" },
      { emoji: "4️⃣", name: "Keycap: 4" },
      { emoji: "5️⃣", name: "Keycap: 5" },
      { emoji: "6️⃣", name: "Keycap: 6" },
      { emoji: "7️⃣", name: "Keycap: 7" },
      { emoji: "8️⃣", name: "Keycap: 8" },
      { emoji: "9️⃣", name: "Keycap: 9" },
      { emoji: "🔟", name: "Keycap: 10" },
      { emoji: "🔢", name: "Input Numbers" },
      { emoji: "#️⃣", name: "Keycap: #" },
      { emoji: "*️⃣", name: "Keycap: *" },
      { emoji: "⏏️", name: "Eject Button" },
      { emoji: "▶️", name: "Play Button" },
      { emoji: "⏸", name: "Pause Button" },
      { emoji: "⏯", name: "Play or Pause Button" },
      { emoji: "⏹", name: "Stop Button" },
      { emoji: "⏺", name: "Record Button" },
      { emoji: "⏭", name: "Next Track Button" },
      { emoji: "⏮", name: "Previous Track Button" },
      { emoji: "⏩", name: "Fast-Forward Button" },
      { emoji: "⏪", name: "Fast Reverse Button" },
      { emoji: "⏫", name: "Fast Up Button" },
      { emoji: "⏬", name: "Fast Down Button" },
      { emoji: "◀️", name: "Reverse Button" },
      { emoji: "🔼", name: "Upwards Button" },
      { emoji: "🔽", name: "Downwards Button" },
      { emoji: "➡️", name: "Right Arrow" },
      { emoji: "⬅️", name: "Left Arrow" },
      { emoji: "⬆️", name: "Up Arrow" },
      { emoji: "⬇️", name: "Down Arrow" },
      { emoji: "↗️", name: "Up-Right Arrow" },
      { emoji: "↘️", name: "Down-Right Arrow" },
      { emoji: "↙️", name: "Down-Left Arrow" },
      { emoji: "↖️", name: "Up-Left Arrow" },
      { emoji: "↕️", name: "Up-Down Arrow" },
      { emoji: "↔️", name: "Left-Right Arrow" },
      { emoji: "↪️", name: "Right Arrow Curving Left" },
      { emoji: "↩️", name: "Left Arrow Curving Left" },
      { emoji: "⤴️", name: "Right Arrow Curving Up" },
      { emoji: "⤵️", name: "Right Arrow Curving Down" },
      { emoji: "🔀", name: "Shuffle Tracks Button" },
      { emoji: "🔁", name: "Repeat Button" },
      { emoji: "🔂", name: "Repeat Single Button" },
      { emoji: "🔄", name: "Counterclockwise Arrows Button" },
      { emoji: "🔃", name: "Clockwise Arrows Button" },
      { emoji: "🎵", name: "Musical Note" },
      { emoji: "🎶", name: "Musical Notes" },
      { emoji: "➕", name: "Plus Sign" },
      { emoji: "➖", name: "Minus Sign" },
      { emoji: "➗", name: "Division Sign" },
      { emoji: "✖️", name: "Multiplication Sign" },
      { emoji: "🟰", name: "Bento Box" },
      { emoji: "♾", name: "Infinity" },
      { emoji: "💲", name: "Heavy Dollar Sign" },
      { emoji: "💱", name: "Currency Exchange" },
      { emoji: "™️", name: "Trade Mark" },
      { emoji: "©️", name: "Copyright" },
      { emoji: "®️", name: "Registered" },
      { emoji: "〰️", name: "Wavy Dash" },
      { emoji: "➰", name: "Curly Loop" },
      { emoji: "➿", name: "Double Curly Loop" },
      { emoji: "🔚", name: "END Arrow" },
      { emoji: "🔙", name: "BACK Arrow" },
      { emoji: "🔛", name: "ON! Arrow" },
      { emoji: "🔝", name: "TOP Arrow" },
      { emoji: "🔜", name: "SOON Arrow" },
      { emoji: "✔️", name: "Check Mark" },
      { emoji: "☑️", name: "Ballot Box with Check" },
      { emoji: "🔘", name: "Radio Button" },
      { emoji: "🔴", name: "Red Circle" },
      { emoji: "🟠", name: "Orange Circle" },
      { emoji: "🟡", name: "Yellow Circle" },
      { emoji: "🟢", name: "Green Circle" },
      { emoji: "🔵", name: "Blue Circle" },
      { emoji: "🟣", name: "Purple Circle" },
      { emoji: "⚫️", name: "Black Circle" },
      { emoji: "⚪️", name: "White Circle" },
      { emoji: "🟤", name: "Brown Circle" },
      { emoji: "🔺", name: "Red Triangle Pointed Up" },
      { emoji: "🔻", name: "Red Triangle Pointed Down" },
      { emoji: "🔸", name: "Small Orange Diamond" },
      { emoji: "🔹", name: "Small Blue Diamond" },
      { emoji: "🔶", name: "Large Orange Diamond" },
      { emoji: "🔷", name: "Large Blue Diamond" },
      { emoji: "🔳", name: "White Square Button" },
      { emoji: "🔲", name: "Black Square Button" },
      { emoji: "▪️", name: "Black Small Square" },
      { emoji: "▫️", name: "White Small Square" },
      { emoji: "◾️", name: "Black Medium-Small Square" },
      { emoji: "◽️", name: "White Medium-Small Square" },
      { emoji: "◼️", name: "Black Medium Square" },
      { emoji: "◻️", name: "White Medium Square" },
      { emoji: "🟥", name: "Red Square" },
      { emoji: "🟧", name: "Orange Square" },
      { emoji: "🟨", name: "Yellow Square" },
      { emoji: "🟩", name: "Green Square" },
      { emoji: "🟦", name: "Blue Square" },
      { emoji: "🟪", name: "Purple Square" },
      { emoji: "⬛️", name: "Black Large Square" },
      { emoji: "⬜️", name: "White Large Square" },
      { emoji: "🟫", name: "Brown Square" },
      { emoji: "🔈", name: "Speaker Low Volume" },
      { emoji: "🔇", name: "Muted Speaker" },
      { emoji: "🔉", name: "Speaker Medium Volume" },
      { emoji: "🔊", name: "Speaker High Volume" },
      { emoji: "🔔", name: "Bell" },
      { emoji: "🔕", name: "Bell with Slash" },
      { emoji: "📣", name: "Megaphone" },
      { emoji: "📢", name: "Loudspeaker" },
      { emoji: "👁‍🗨", name: "Eye in Speech Bubble" },
      { emoji: "💬", name: "Speech Balloon" },
      { emoji: "💭", name: "Thought Balloon" },
      { emoji: "🗯", name: "Right Anger Bubble" },
      { emoji: "♠️", name: "Spade Suit" },
      { emoji: "♣️", name: "Club Suit" },
      { emoji: "♥️", name: "Heart Suit" },
      { emoji: "♦️", name: "Diamond Suit" },
      { emoji: "🃏", name: "Joker" },
      { emoji: "🎴", name: "Flower Playing Cards" },
      { emoji: "🀄️", name: "Mahjong Red Dragon" },
      { emoji: "🕐", name: "One O’Clock" },
      { emoji: "🕑", name: "Two O’Clock" },
      { emoji: "🕒", name: "Three O’Clock" },
      { emoji: "🕓", name: "Four O’Clock" },
      { emoji: "🕔", name: "Five O’Clock" },
      { emoji: "🕕", name: "Six O’Clock" },
      { emoji: "🕖", name: "Seven O’Clock" },
      { emoji: "🕗", name: "Eight O’Clock" },
      { emoji: "🕘", name: "Nine O’Clock" },
      { emoji: "🕙", name: "Ten O’Clock" },
      { emoji: "🕚", name: "Eleven O’Clock" },
      { emoji: "🕛", name: "Twelve O’Clock" },
      { emoji: "🕜", name: "One-Thirty" },
      { emoji: "🕝", name: "Two-Thirty" },
      { emoji: "🕞", name: "Three-Thirty" },
      { emoji: "🕟", name: "Four-Thirty" },
      { emoji: "🕠", name: "Five-Thirty" },
      { emoji: "🕡", name: "Six-Thirty" },
      { emoji: "🕢", name: "Seven-Thirty" },
      { emoji: "🕣", name: "Eight-Thirty" },
      { emoji: "🕤", name: "Nine-Thirty" },
      { emoji: "🕥", name: "Ten-Thirty" },
      { emoji: "🕦", name: "Eleven-Thirty" },
      { emoji: "🕧", name: "Twelve-Thirty" },
    ],
  },
  {
    groupName: "flags",
    groupLogo: <IoFlagSharp />,
    emojis: [
      { countryCode: "AF", name: "Afghanistan" },
      { countryCode: "AL", name: "Albania" },
      { countryCode: "DZ", name: "Algeria" },
      { countryCode: "AD", name: "Andorra" },
      { countryCode: "AO", name: "Angola" },
      { countryCode: "AG", name: "Antigua & Barbuda" },
      { countryCode: "AR", name: "Argentina" },
      { countryCode: "AM", name: "Armenia" },
      { countryCode: "AU", name: "Australia" },
      { countryCode: "AT", name: "Austria" },
      { countryCode: "AZ", name: "Azerbaijan" },
      { countryCode: "BS", name: "Bahamas" },
      { countryCode: "BH", name: "Bahrain" },
      { countryCode: "BD", name: "Bangladesh" },
      { countryCode: "BB", name: "Barbados" },
      { countryCode: "BY", name: "Belarus" },
      { countryCode: "BE", name: "Belgium" },
      { countryCode: "BZ", name: "Belize" },
      { countryCode: "BJ", name: "Benin" },
      { countryCode: "BT", name: "Bhutan" },
      { countryCode: "BO", name: "Bolivia" },
      { countryCode: "BA", name: "Bosnia & Herzegovina" },
      { countryCode: "BW", name: "Botswana" },
      { countryCode: "BR", name: "Brazil" },
      { countryCode: "BN", name: "Brunei" },
      { countryCode: "BG", name: "Bulgaria" },
      { countryCode: "BF", name: "Burkina Faso" },
      { countryCode: "BI", name: "Burundi" },
      { countryCode: "KH", name: "Cambodia" },
      { countryCode: "CM", name: "Cameroon" },
      { countryCode: "CA", name: "Canada" },
      { countryCode: "CV", name: "Cape Verde" },
      { countryCode: "CF", name: "Central African Republic" },
      { countryCode: "TD", name: "Chad" },
      { countryCode: "CL", name: "Chile" },
      { countryCode: "CN", name: "China" },
      { countryCode: "CO", name: "Colombia" },
      { countryCode: "KM", name: "Comoros" },
      { countryCode: "CD", name: "Congo - Kinshasa" },
      { countryCode: "CG", name: "Congo - Brazzaville" },
      { countryCode: "CR", name: "Costa Rica" },
      { countryCode: "HR", name: "Croatia" },
      { countryCode: "CU", name: "Cuba" },
      { countryCode: "CY", name: "Cyprus" },
      { countryCode: "CZ", name: "Czech Republic" },
      { countryCode: "DK", name: "Denmark" },
      { countryCode: "DJ", name: "Djibouti" },
      { countryCode: "DM", name: "Dominica" },
      { countryCode: "DO", name: "Dominican Republic" },
      { countryCode: "EC", name: "Ecuador" },
      { countryCode: "EG", name: "Egypt" },
      { countryCode: "SV", name: "El Salvador" },
      { countryCode: "GB-ENG", name: "England" },
      { countryCode: "GQ", name: "Equatorial Guinea" },
      { countryCode: "ER", name: "Eritrea" },
      { countryCode: "EE", name: "Estonia" },
      { countryCode: "SZ", name: "Eswatini" },
      { countryCode: "ET", name: "Ethiopia" },
      { countryCode: "FJ", name: "Fiji" },
      { countryCode: "FI", name: "Finland" },
      { countryCode: "FR", name: "France" },
      { countryCode: "GA", name: "Gabon" },
      { countryCode: "GM", name: "Gambia" },
      { countryCode: "GE", name: "Georgia" },
      { countryCode: "DE", name: "Germany" },
      { countryCode: "GH", name: "Ghana" },
      { countryCode: "GR", name: "Greece" },
      { countryCode: "GD", name: "Grenada" },
      { countryCode: "GT", name: "Guatemala" },
      { countryCode: "GN", name: "Guinea" },
      { countryCode: "GW", name: "Guinea-Bissau" },
      { countryCode: "GY", name: "Guyana" },
      { countryCode: "HT", name: "Haiti" },
      { countryCode: "HN", name: "Honduras" },
      { countryCode: "HU", name: "Hungary" },
      { countryCode: "IS", name: "Iceland" },
      { countryCode: "IN", name: "India" },
      { countryCode: "ID", name: "Indonesia" },
      { countryCode: "IR", name: "Iran" },
      { countryCode: "IQ", name: "Iraq" },
      { countryCode: "IE", name: "Ireland" },
      { countryCode: "IL", name: "Israel" },
      { countryCode: "IT", name: "Italy" },
      { countryCode: "JM", name: "Jamaica" },
      { countryCode: "JP", name: "Japan" },
      { countryCode: "JO", name: "Jordan" },
      { countryCode: "KZ", name: "Kazakhstan" },
      { countryCode: "KE", name: "Kenya" },
      { countryCode: "KI", name: "Kiribati" },
      { countryCode: "KP", name: "North Korea" },
      { countryCode: "KR", name: "South Korea" },
      { countryCode: "XK", name: "Kosovo" },
      { countryCode: "KW", name: "Kuwait" },
      { countryCode: "KG", name: "Kyrgyzstan" },
      { countryCode: "LA", name: "Laos" },
      { countryCode: "LV", name: "Latvia" },
      { countryCode: "LB", name: "Lebanon" },
      { countryCode: "LS", name: "Lesotho" },
      { countryCode: "LR", name: "Liberia" },
      { countryCode: "LY", name: "Libya" },
      { countryCode: "LI", name: "Liechtenstein" },
      { countryCode: "LT", name: "Lithuania" },
      { countryCode: "LU", name: "Luxembourg" },
      { countryCode: "MG", name: "Madagascar" },
      { countryCode: "MW", name: "Malawi" },
      { countryCode: "MY", name: "Malaysia" },
      { countryCode: "MV", name: "Maldives" },
      { countryCode: "ML", name: "Mali" },
      { countryCode: "MT", name: "Malta" },
      { countryCode: "MH", name: "Marshall Islands" },
      { countryCode: "MR", name: "Mauritania" },
      { countryCode: "MU", name: "Mauritius" },
      { countryCode: "MX", name: "Mexico" },
      { countryCode: "FM", name: "Micronesia" },
      { countryCode: "MD", name: "Moldova" },
      { countryCode: "MC", name: "Monaco" },
      { countryCode: "MN", name: "Mongolia" },
      { countryCode: "ME", name: "Montenegro" },
      { countryCode: "MA", name: "Morocco" },
      { countryCode: "MZ", name: "Mozambique" },
      { countryCode: "MM", name: "Myanmar (Burma)" },
      { countryCode: "NA", name: "Namibia" },
      { countryCode: "NR", name: "Nauru" },
      { countryCode: "NP", name: "Nepal" },
      { countryCode: "NL", name: "Netherlands" },
      { countryCode: "NZ", name: "New Zealand" },
      { countryCode: "NI", name: "Nicaragua" },
      { countryCode: "NE", name: "Niger" },
      { countryCode: "NG", name: "Nigeria" },
      { countryCode: "NO", name: "Norway" },
      { countryCode: "GB-NIR", name: "Northern Ireland" },
      { countryCode: "OM", name: "Oman" },
      { countryCode: "PK", name: "Pakistan" },
      { countryCode: "PW", name: "Palau" },
      { countryCode: "PA", name: "Panama" },
      { countryCode: "PG", name: "Papua New Guinea" },
      { countryCode: "PY", name: "Paraguay" },
      { countryCode: "PE", name: "Peru" },
      { countryCode: "PH", name: "Philippines" },
      { countryCode: "PL", name: "Poland" },
      { countryCode: "PT", name: "Portugal" },
      { countryCode: "QA", name: "Qatar" },
      { countryCode: "RO", name: "Romania" },
      { countryCode: "RU", name: "Russia" },
      { countryCode: "RW", name: "Rwanda" },
      { countryCode: "KN", name: "Saint Kitts & Nevis" },
      { countryCode: "LC", name: "Saint Lucia" },
      { countryCode: "VC", name: "Saint Vincent & Grenadines" },
      { countryCode: "WS", name: "Samoa" },
      { countryCode: "SM", name: "San Marino" },
      { countryCode: "ST", name: "Sao Tome & Principe" },
      { countryCode: "SA", name: "Saudi Arabia" },
      { countryCode: "SN", name: "Senegal" },
      { countryCode: "RS", name: "Serbia" },
      { countryCode: "SC", name: "Seychelles" },
      { countryCode: "SL", name: "Sierra Leone" },
      { countryCode: "SG", name: "Singapore" },
      { countryCode: "SK", name: "Slovakia" },
      { countryCode: "SI", name: "Slovenia" },
      { countryCode: "SB", name: "Solomon Islands" },
      { countryCode: "SO", name: "Somalia" },
      { countryCode: "ZA", name: "South Africa" },
      { countryCode: "SS", name: "South Sudan" },
      { countryCode: "ES", name: "Spain" },
      { countryCode: "LK", name: "Sri Lanka" },
      { countryCode: "SD", name: "Sudan" },
      { countryCode: "SR", name: "Suriname" },
      { countryCode: "SE", name: "Sweden" },
      { countryCode: "CH", name: "Switzerland" },
      { countryCode: "SY", name: "Syria" },
      { countryCode: "TW", name: "Taiwan" },
      { countryCode: "TJ", name: "Tajikistan" },
      { countryCode: "TZ", name: "Tanzania" },
      { countryCode: "TH", name: "Thailand" },
      { countryCode: "TL", name: "Timor-Leste" },
      { countryCode: "TG", name: "Togo" },
      { countryCode: "TO", name: "Tonga" },
      { countryCode: "TT", name: "Trinidad & Tobago" },
      { countryCode: "TN", name: "Tunisia" },
      { countryCode: "TR", name: "Turkey" },
      { countryCode: "TM", name: "Turkmenistan" },
      { countryCode: "TV", name: "Tuvalu" },
      { countryCode: "UG", name: "Uganda" },
      { countryCode: "UA", name: "Ukraine" },
      { countryCode: "AE", name: "United Arab Emirates" },
      { countryCode: "GB", name: "United Kingdom" },
      { countryCode: "US", name: "United States" },
      { countryCode: "UY", name: "Uruguay" },
      { countryCode: "UZ", name: "Uzbekistan" },
      { countryCode: "VU", name: "Vanuatu" },
      { countryCode: "VA", name: "Vatican City" },
      { countryCode: "VE", name: "Venezuela" },
      { countryCode: "VN", name: "Vietnam" },
      { countryCode: "YE", name: "Yemen" },
      { countryCode: "ZM", name: "Zambia" },
      { countryCode: "ZW", name: "Zimbabwe" },
    ],
  },
];
